### ISSUE TITLE
Refresh bug with profiles on opensats.org/about 

### ISSUE THREAD

**Issue by Arvin21M** [OpenSats/website#170]
@dergigi 

**OpenSats website>About page:**

There is a bug when the page is refreshed; when a members profile is clicked after refresh, often another members profile opens. Seems to only be happening when refreshing. Recorded screen of the issue to help you duplicate the bug on your end. [Click here](https://www.dropbox.com/scl/fi/ruaa3y1c77c5h5cefq5sp/2023-11-03_OpenSats-website.mp4?rlkey=cic4cx3quro0zitu4a7fryhm9&dl=0) to watch the recording. Let me know how I can help.

Thank you.

**Comment by dergigi** [comment]
Damn. I was able to reproduce this in production.

@moteanup24 maybe you can have a look at this and try to track down the bug?

**Comment by bitcoinprecept** [comment]
Not sure if it's related, but I noticed the order of icons changes whenever you refresh the page. If this behavior is not intentional, it could be related.

**Comment by moteanup24** [comment]
@dergigi 

Update: I'm pretty sure the bug is occurring because the randomization in getStaticProps() in pages/about/index.tsx is not being propagated down through to the MDXComponents. You'll notice that the randomization is repeated in components/BoardMembers as well as ./OpsTeam and ./Volunteers. So I think multiple Math.random() calls is causing the issue.

I think what we want is to create a randomized 'master' author array as a static prop in index.tsx, and pass it through MDXLayoutRenderer to the MDXComponents so that when the {openSats} content renders, it does so with the static randomized author array. Unfortunately I haven't been able to figure out how to pass the static props through to MDX components...

Unless I'm missing a quick way to do this (I am still getting familiar with MDX) I'd be inclined to just do away with the randomization on the about page. I also tried rewriting the about/index page using more vanilla jsx which seems to allow for more straightforward passing of props, which is do-able but then would require more manual formatting.

This is probably entirely too long for your taste but I wanted to provide an update and give you a chance to weigh in.

**Comment by moteanup24** [comment]
#187
