### ISSUE TITLE
Prefix generic titles by individual

### ISSUE THREAD

**Issue by jamesob** [OpenSats/website#99]
![image](https://user-images.githubusercontent.com/73197/236832890-a14d5782-a5c2-4796-83ad-d486c5760346.png)

Titles like "Core maintenance" and "Core review & testing" could be mistaken for generic efforts across multiple people rather than for specific individuals. I think titles like these should be prefixed by "[person's name]: " to avoid confusion.

**Comment by dergigi** [comment]
I think this has to be solved in another way, otherwise we risk (a) inviting a popularity contest, and/or (b) re-creating a worse version of Patreon.

Our grant program will fix this, and we should also make it clear that part of our "General Fund" is directed towards core. I think we could also list "Bitcoin Core" as a project to make this support more clear and have a way for people to "earmark" funds towards core more clearly.
